const fs = require("fs");
const assert = require("assert");

const html = fs.readFileSync("C:/Users/kim16/Videos/Pulseboard/index.html", "utf8");

function expect(pattern, description) {
  assert.match(html, pattern, description);
}

expect(/id="apiKeyPage"/, "expected a dedicated API key page");
expect(/id="connectionForm"/, "expected a dedicated connection form");
expect(/id="providerSelect"/, "expected a provider select field");
expect(/NVIDIA API \(Recommended\)/, "expected NVIDIA to be labeled as recommended in the provider dropdown");
expect(/<option value="nvidia" selected>NVIDIA API \(Recommended\)<\/option>/, "expected NVIDIA to be the default selected provider");
expect(/provider-help-recommended\">Recommended<\/span><span>NVIDIA API<\/span>/, "expected the NVIDIA help card to show a Recommended badge before NVIDIA API");
expect(/id="providerHelpShortcut"/, "expected a shortcut link to the provider help section");
expect(/API Key[\s\S]*\(No API keys\? Get here\)/i, "expected API key help shortcut copy inline with the API key label");
expect(/function handleProviderHelpShortcutClick\(/, "expected smooth-scroll handler for provider help shortcut");
expect(/id="providerAdvancedSettings"/, "expected advanced settings disclosure for provider model and endpoint");
expect(/Advanced settings/i, "expected advanced settings toggle copy on the API key form");
expect(/#connectionFormMessage\s*\{[\s\S]*margin-top:\s*8px/i, "expected spacing between provider notes and the connection message");
expect(/id="homePage"/, "expected a dedicated home page section");
expect(/id="homeExplanation"/, "expected a dedicated home explanation section");
expect(/id="guidePage"/, "expected a dedicated guide page section");
expect(/id="guideButton"/, "expected a navbar guide entry");
expect(/body\.home-dark-mode\s*\{[\s\S]*background:/i, "expected a home-only dark mode body theme hook");
expect(/body\.home-dark-mode \.topbar[\s\S]*body\.home-dark-mode #homePage/i, "expected dark mode overrides to be scoped to the landing-page shell");
expect(/5 agents fire simultaneously/i, "expected home explainer content below the hero");
expect(/PulseBoard turns scattered market signals and internal data into decision-ready briefs\./i, "expected sharper landing-page value proposition copy");
expect(/Built for students, analysts, and operators/i, "expected sharper landing-page audience framing");
expect(/How to Use PulseBoard/i, "expected guide-page practical walkthrough heading");
expect(/Ask PulseBoard/i, "expected guide page to include the Ask PulseBoard walkthrough");
expect(/floating follow-up chat/i, "expected guide page to describe Ask PulseBoard as a floating chat");
expect(/uses fresh live follow-up search when it is not/i, "expected guide page to explain monitoring follow-up search escalation");
expect(/exact matching rows inline/i, "expected guide page to explain CSV row retrieval in Ask PulseBoard");
expect(/See all rows/i, "expected guide page to mention CSV row expansion behavior in the guide");
expect(/Recent Monitoring Runs/i, "expected guide page to include monitoring history walkthrough");
expect(/Cross-Reference Internal and External Signals/i, "expected guide page to include the CSV cross-reference workflow");
expect(/function syncHomeExplanationState\(/, "expected a home explanation collapse helper");
expect(/homeTheme:\s*"light"/, "expected landing-page theme state to default to light");
expect(/function toggleHomeTheme\(/, "expected a landing-page theme toggle handler");
expect(/function syncHomeThemeUi\(/, "expected a home theme UI sync helper");
expect(/\.hero-grid \{ grid-template-columns: minmax\(0,1\.42fr\) minmax\(300px,0\.58fr\); align-items: stretch; \}/, "expected landing hero desktop columns to widen the signal rail slightly while preserving the broader headline layout");
expect(/\.hero-title \{ font-size: clamp\(34px, 5\.4vw, 58px\); line-height: 1\.04; max-width: 18ch; \}/, "expected hero headline width to be relaxed for wider desktop wrapping");
expect(/\.hero-subtitle \{ margin: 14px 0 0; max-width: 60ch; color: var\(--text-secondary\); \}/, "expected hero subtitle measure to widen slightly with the broader headline block");
assert.doesNotMatch(html, /id="homeThemeToggleButton"/, "expected the landing-page dark mode toggle button to be hidden for now");
assert.doesNotMatch(html, /homeThemeToggleButton\?\.addEventListener\("click", toggleHomeTheme\)/, "expected the landing-page dark mode toggle click binding to be disabled for now");
expect(/transition:\s*max-height\s+0\.35s\s+ease/i, "expected smooth home explanation collapse transition");
expect(/id="queryPage"/, "expected a dedicated query page section");
expect(/id="runHistorySection"/, "expected a monitoring run history section on the New Query screen");
expect(/id="scenarioLauncher"/, "expected a floating scenario simulator launcher");
expect(/id="scenarioWindow"/, "expected a floating scenario simulator window shell");
expect(/id="scenarioMessages"/, "expected a scenario chat message list");
expect(/id="scenarioForm"/, "expected a scenario chat form");
expect(/id="scenarioQuestionInput"/, "expected a scenario question input");
expect(/id="csvPage"/, "expected a dedicated csv page section");
expect(/<option value="interviewprep">Interview Prep<\/option>/, "expected interview prep mode in the query mode dropdown");
expect(/id="interviewRoleGroup"/, "expected an interview role input group");
expect(/id="roleInput"/, "expected a dedicated role input for interview prep");
expect(/scripts\/csv-schema\.js/, "expected the page to load extracted csv schema helpers");
expect(/scripts\/csv-analytics\.js/, "expected the page to load extracted csv analytics helpers");
expect(/scripts\/csv-logging\.js/, "expected the page to load extracted csv logging helpers");
expect(/function getRouteFromLocation\(/, "expected a route parser");
expect(/function navigateTo\(/, "expected a navigation helper");
expect(/function applyRouteState\(/, "expected a route-driven visibility handler");
expect(/document\.body\.classList\.toggle\("home-dark-mode",\s*showHome\s*&&\s*state\.homeTheme\s*===\s*"dark"\)/, "expected home dark mode to apply only on the landing page");
expect(/function saveConnectionFromForm\(/, "expected a saveConnectionFromForm function");
expect(/runHistory:\s*\[\]/, "expected monitoring run history state");
expect(/selectedHistoryRunId:\s*null/, "expected selected history run state");
expect(/runHistoryCollapsed:\s*false/, "expected run history collapse state to default to expanded");
expect(/scenarioThreads:\s*\{\}/, "expected per-run scenario thread state");
expect(/scenarioWindow:\s*\{[\s\S]*open:\s*false[\s\S]*minimized:\s*false[\s\S]*width:\s*\d+[\s\S]*height:\s*\d+/i, "expected scenario window UI state");
expect(/function serializeMonitoringRunForHistory\(/, "expected helper to serialize monitoring runs for history");
expect(/function loadRunHistory\(/, "expected helper to load monitoring history from localStorage");
expect(/function saveRunHistory\(/, "expected helper to persist monitoring history");
expect(/function getPreviousComparableRun\(/, "expected helper to find the previous comparable monitoring run");
expect(/function buildChangeDetectionSummary\(/, "expected helper to compute change detection");
expect(/function renderRunHistorySection\(/, "expected helper to render monitoring history");
expect(/function restoreMonitoringRunFromHistory\(/, "expected helper to restore a saved monitoring run");
expect(/function getScenarioRunId\(/, "expected active scenario run helper");
expect(/function getCsvScenarioResultId\(/, "expected CSV scenario result helper");
expect(/function getActiveScenarioContext\(/, "expected shared scenario context helper");
expect(/function syncScenarioVisibility\(/, "expected scenario launcher visibility helper");
expect(/function renderScenarioWindow\(/, "expected scenario window renderer");
expect(/function submitScenarioQuestion\(/, "expected scenario question submit handler");
expect(/function handleScenarioMessagesClick\(/, "expected scenario inline action handler");
expect(/function hasScenarioSignalCount\(signalCount\)/, "expected scenario signal-count helper");
expect(/localStorage/i, "expected monitoring history to use browser localStorage");
expect(/What Changed Since Last Run/i, "expected a change-detection panel title");
expect(/function renderFreshnessPill\(/, "expected freshness tag renderer for live intelligence surfaces");
expect(/function renderConfidencePill\(/, "expected confidence badge renderer for live intelligence surfaces");
expect(/function renderReliabilitySummary\(/, "expected reliability summary renderer for monitoring and interview briefs");
expect(/based on \$\{escapeHtml\(String\(reliability\.sourceCount/i, "expected brief reliability messaging to include based on X signals copy");
expect(/partial evidence|some agents or searches failed|partial coverage/i, "expected partial-run transparency messaging in the UI");
expect(/verified-working links|verified links|link verification/i, "expected verified-link handling hooks in the UI");
expect(/const partialCopy = reliability\.partialCoverage[\s\S]*some agents or searches failed[\s\S]*: "";/, "expected partial-evidence UI copy to be gated by the true partialCoverage flag");
expect(/function renderFreshnessPill\(value\) \{[\s\S]*normalized === "unknown"\) return "";/, "expected Unknown freshness tags to be suppressed");
expect(/function renderConfidencePill\(value\) \{[\s\S]*normalized === "unknown"\) return "";/, "expected Unknown confidence tags to be suppressed");
assert.doesNotMatch(html, /Unknown freshness/, "expected Unknown freshness pill copy to be removed from the UI");
expect(/\.history-section \.secondary-button,\s*[\s\S]*\.history-section \.ghost-button\s*\{[\s\S]*border-radius:\s*10px/i, "expected history action buttons to use a 10px border radius");
expect(/data-history-action="toggle-collapse"/, "expected a collapse\/expand control in the run history header");
expect(/function normalizeMetricValue\(/, "expected metric normalization helper for model-returned scores");
expect(/function renderMetricDirectionHint\(/, "expected metric direction hint renderer");
expect(/function renderIcon\(/, "expected shared inline SVG icon helper");
expect(/function runProviderRequest\(/, "expected a provider-agnostic request dispatcher");
expect(/function buildProviderRequest\(/, "expected provider request builders");
expect(/function parseProviderResponse\(/, "expected provider response parsers");
expect(/provider:\s*"openai"\s*\|\s*"anthropic"\s*\|\s*"gemini"\s*\|\s*"nvidia"/, "expected normalized provider shape documentation");
expect(/higher is better/i, "expected positive metric direction guidance in the UI");
expect(/lower is better/i, "expected negative metric direction guidance in the UI");
expect(/"\//, "expected root route handling in the UI");
expect(/["']\/guide["']/, "expected guide route handling in the UI");
expect(/["']\/query["']/, "expected query route handling in the UI");
expect(/["']\/csv["']/, "expected csv route handling in the UI");
expect(/["']\/api-key["']/, "expected api-key route handling in the UI");
expect(/\.agent-card\s*\{[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column/i, "expected agent cards to use consistent internal column layout");
expect(/\.mini-panel\s*\{[\s\S]*min-height:\s*\d+px/i, "expected mini panels to enforce consistent tile height");
expect(/\.section-intro\s*\{[\s\S]*display:\s*flex/i, "expected shared section intro alignment helper");
expect(/#queryPage \.utility-row\s*\{[\s\S]*flex-wrap:\s*nowrap/i, "expected query utility row to stay on one row at desktop widths");
expect(/#queryPage #statusMessage\s*\{[\s\S]*border-radius:\s*10px/i, "expected query status message to use a 10px border radius");
expect(/#queryPage #statusMessage\s*\{[\s\S]*margin-top:\s*26px/i, "expected query status message to align with the demo-topic chip row while staying in the same row");
expect(/\.aggregator-banner\s*\{[\s\S]*?border-radius:\s*10px/i, "expected the New Query aggregator banner to use a 10px border radius");
expect(/#csvPage\.query-panel\s*\{[\s\S]*border-radius:\s*10px/i, "expected CSV Analyst card to use a 10px border radius");
expect(/#csvResultSection\.brief-section\s*\{[\s\S]*border-radius:\s*10px/i, "expected generated CSV analysis card to use a 10px border radius");
expect(/#csvStatusMessage\s*\{[\s\S]*border-radius:\s*10px/i, "expected CSV status message to use a 10px border radius");
expect(/function renderCsvComparisonResult\(result, meta\) \{[\s\S]*brief-summary csv-summary-callout brief-card[\s\S]*Key Insight[\s\S]*file-overview-grid/, "expected compare-view Key Insight to use the single-file summary-callout style before file overview content");
expect(/\.quality-progress\s*\{[\s\S]*height:\s*4px[\s\S]*display:\s*flex/i, "expected normalized quality-progress sizing for equal bar heights");
expect(/\.quality-progress-fill\s*\{[\s\S]*height:\s*100%[\s\S]*display:\s*block/i, "expected quality-progress-fill to fully match the normalized track height");
expect(/\.quality-score-number\s*\{[\s\S]*dominant-baseline:\s*middle/i, "expected the CSV quality score text to be vertically centered");
expect(/class="quality-score-number" x="28" y="28"/, "expected the main CSV quality score number to sit in the middle of the ring");
expect(/<text x="20" y="20" style="font-size:10px;font-weight:500;fill:#1a1a2e;text-anchor:middle;dominant-baseline:middle;">\$\{escapeHtml\(quality\.overallScore\)\}<\/text>/, "expected compare-view mini quality ring text to be centered");
assert.doesNotMatch(html, /<h2 class="section-title" id="csvResultHeading" style="font-size:32px;">CSV Comparison Brief<\/h2>/, "expected the visible CSV Comparison Brief heading to be removed from compare view");
expect(/\.ui-icon\s*\{[\s\S]*display:\s*inline-block/i, "expected shared SVG icon styling");
expect(/\.tier-dot\s*\{[\s\S]*border-radius:\s*50%/i, "expected glossy tier dot styling for brief headings");
expect(/function renderTierDot\(kind\)/, "expected a dedicated tier dot helper for monitoring brief headings");
expect(/class="tier-title">\$\{renderTierDot\(kind\)\}<span>\$\{title\}<\/span>/, "expected monitoring brief headings to use tier dots instead of shared SVG icons");
expect(/id="brandMarkIcon"/, "expected the navbar brand mark to use an icon placeholder");
expect(/id="aggregatorBannerIcon"/, "expected the aggregator banner to use an icon placeholder");
expect(/class="button-icon"/, "expected the run button to use an icon wrapper");
expect(/function renderJobsMarkup\(/, "expected jobs card renderer");
expect(/Career Links/i, "expected jobs card to support careers and posting links");
expect(/<strong>Score<\/strong>[\s\S]*<strong>Velocity<\/strong>/, "expected Job Signal Tracker tiles to render Score before Velocity");
expect(/<strong>ESG<\/strong>[\s\S]*<strong>Risk<\/strong>/, "expected Regulatory & ESG Scanner tiles to render ESG before Risk");
expect(/\.agent-card-icon\s*\{[\s\S]*width:\s*44px[\s\S]*height:\s*44px[\s\S]*border-radius:\s*16px/i, "expected a shared dashboard agent icon container style");
expect(/class="brand-mark agent-card-icon"/, "expected agent dashboard cards to use the shared icon container class");
expect(/function normalizeJobLink\(/, "expected jobs link normalizer");
expect(/function resolveNewsSignalStrength\(/, "expected news signal-strength fallback helper");
expect(/function extractRelayErrorInfo\(/, "expected normalized relay error reader in the dashboard");
expect(/function buildFriendlyRelayErrorMessage\(/, "expected concise monitoring error messaging in the UI");
expect(/function setAgentCardVisibility\(/, "expected agent-card visibility helper for empty results");
expect(/function renderOptionalInfoNote\(/, "expected optional monitoring note renderer");
expect(/function renderOptionalTagRow\(/, "expected optional tag-row renderer");
expect(/function joinMarkupSections\(/, "expected monitoring card section join helper");
assert.doesNotMatch(html, /label:\s*"Sikich"/, "expected Sikich to be removed from New Query demo topics");
assert.doesNotMatch(html, /label:\s*"pharma industry"/i, "expected pharma industry to be removed from New Query demo topics");
assert.doesNotMatch(html, /No hot roles returned|No hiring signal returned|No opportunity signal returned|No recent headlines returned|No candidate themes surfaced|No peer interview patterns returned/, "expected monitoring cards to hide empty content instead of showing filler placeholders");
expect(/function syncQueryModeUi\(/, "expected query mode UI sync helper");
expect(/function getActiveAgentConfigs\(/, "expected mode-aware agent card configuration");
expect(/setRunButtonIdleState\(/, "expected a reusable idle-state renderer for the run button");
expect(/setRunButtonLoadingState\(/, "expected a reusable loading-state renderer for the run button");
expect(/function renderInterviewPrepBrief\(/, "expected a dedicated interview prep brief renderer");
expect(/function renderInterviewPrepNewsMarkup\(/, "expected interview prep agent card renderers");
expect(/mode !== "interviewprep"[\s\S]*saveMonitoringRunToHistory|if\s*\(state\.mode\s*===\s*"interviewprep"\)\s*return/i, "expected monitoring history persistence to exclude interview prep");
expect(/Interview Prep Brief/i, "expected interview prep brief heading copy");
expect(/function renderInterviewPrepBrief\(result\) \{[\s\S]*brief-header[\s\S]*brief-header-side[\s\S]*Interview Prep Brief/i, "expected interview prep brief to use the shared brief header shell");
expect(/function renderInterviewPrepBrief\(result\) \{[\s\S]*csv-action-bar action-bar[\s\S]*Copy Summary[\s\S]*Download Brief/i, "expected interview prep brief to use the bottom action bar pattern");
assert.doesNotMatch(html, /function renderInterviewPrepBrief\(result\) \{[\s\S]*<div class="brief-actions"><button class="secondary-button" type="button" id="copyBriefButton">Copy to Clipboard<\/button><button class="secondary-button" type="button" id="downloadBriefButton">Download Brief<\/button>/, "expected interview prep brief to remove the old top-right brief-actions button row");
assert.doesNotMatch(html, /function renderInterviewPrepBrief\(result\) \{[\s\S]*<div class="score-card"><div class="score-label">Confidence<\/div>/, "expected interview prep brief to remove the confidence score card");
expect(/state\.route === "csv" && state\.csvResultVisible && state\.csvExportMode === "single"/, "expected scenario context to support single-file CSV analysis results");
expect(/scenarioType:\s*"interview_prep"/, "expected Ask PulseBoard to define a dedicated interview prep scenario context");
expect(/Interview prep: \$\{state\.topic\}\$\{state\.role \? ` - \$\{state\.role\}` : ""\}/, "expected Interview Prep scenario subtitle to include the company and target role");
expect(/Ask anything about this interview-prep brief\./, "expected scenario empty state copy for interview prep follow-up questions");
expect(/Answers stay tied to this interview prep run\./, "expected scenario status copy for interview prep runs");
expect(/context\?\.scenarioType === "interview_prep" \? state\.role : undefined/, "expected scenario payload building to send the target role for interview prep follow-ups");
expect(/function renderCsvAnalysisResult\(result, sourceLabel\) \{[\s\S]*syncScenarioVisibility\(\);/s, "expected single-file CSV rendering to recompute scenario launcher visibility");
expect(/function renderInterviewPrepBrief\(result\) \{[\s\S]*syncScenarioVisibility\(\);/s, "expected interview prep rendering to recompute scenario launcher visibility");
expect(/fetch\(["'`]\/api\/pulseboard\/scenario["'`]/, "expected frontend to call the scenario relay endpoint");
expect(/reliability:\s*brief\?\.reliability\s*\|\|\s*null/, "expected scenario payload building to guard reliability access when CSV mode has no monitoring brief");
expect(/\.scenario-window\s*\{[\s\S]*position:\s*fixed/i, "expected a fixed-position scenario window style");
expect(/\.scenario-resize-handle\s*\{[\s\S]*cursor:\s*nwse-resize/i, "expected a visible resize handle for the scenario window");
expect(/data-scenario-source="\$\{escapeHtml\(sourceModeLabel\)\}"/, "expected scenario messages to carry provenance labels");
expect(/hasScenarioSignalCount\(message\.signalCount\) \? `<span class="scenario-source-pill">Based on \$\{escapeHtml\(String\(message\.signalCount\)\)\} signals<\/span>` : ""/, "expected scenario signal pill to render only for valid numeric counts");
expect(/scenario-row-table|scenario-inline-action|See all rows/i, "expected CSV scenario chat to support inline row tables and expansion actions");
expect(/restored context for Ask PulseBoard when you reopen a saved monitoring snapshot/i, "expected guide page to explain Ask PulseBoard context restoration for saved monitoring runs");
expect(/follow-up chat through Ask PulseBoard after the first analysis is complete/i, "expected guide page to explain CSV Analyst follow-up chat coverage");
expect(/icon:\s*"news"|icon:\s*"jobs"|icon:\s*"sentiment"|icon:\s*"regulatory"|icon:\s*"competitor"/, "expected agent configs to use semantic icon names");
assert.doesNotMatch(html, /â—Œ|ðŸ|âš¡/, "expected broken mojibake icon glyphs to be removed from the monitoring UI");

console.log("PulseBoard structure assertions passed.");
