const fs = require("fs");
const assert = require("assert");

const html = fs.readFileSync("C:/Users/kim16/Videos/Pulseboard/index.html", "utf8");

function expect(pattern, description) {
  assert.match(html, pattern, description);
}

expect(/id="apiKeyPage"/, "expected a dedicated API key page");
expect(/id="connectionForm"/, "expected a dedicated connection form");
expect(/id="providerSelect"/, "expected a provider select field");
expect(/NVIDIA API \(Recommended\)/, "expected NVIDIA to be labeled as recommended in the provider dropdown");
expect(/<option value="nvidia" selected>NVIDIA API \(Recommended\)<\/option>/, "expected NVIDIA to be the default selected provider");
expect(/provider-help-recommended\">Recommended<\/span><span>NVIDIA API<\/span>/, "expected the NVIDIA help card to show a Recommended badge before NVIDIA API");
expect(/id="providerHelpShortcut"/, "expected a shortcut link to the provider help section");
expect(/API Key[\s\S]*\(No API keys\? Get here\)/i, "expected API key help shortcut copy inline with the API key label");
expect(/function handleProviderHelpShortcutClick\(/, "expected smooth-scroll handler for provider help shortcut");
expect(/id="providerAdvancedSettings"/, "expected advanced settings disclosure for provider model and endpoint");
expect(/Advanced settings/i, "expected advanced settings toggle copy on the API key form");
expect(/#connectionFormMessage\s*\{[\s\S]*margin-top:\s*8px/i, "expected spacing between provider notes and the connection message");
expect(/id="homePage"/, "expected a dedicated home page section");
expect(/id="homeExplanation"/, "expected a dedicated home explanation section");
expect(/body\.home-dark-mode\s*\{[\s\S]*background:/i, "expected a home-only dark mode body theme hook");
expect(/body\.home-dark-mode \.topbar[\s\S]*body\.home-dark-mode #homePage/i, "expected dark mode overrides to be scoped to the landing-page shell");
expect(/5 agents fire simultaneously/i, "expected home explainer content below the hero");
expect(/function syncHomeExplanationState\(/, "expected a home explanation collapse helper");
expect(/homeTheme:\s*"light"/, "expected landing-page theme state to default to light");
expect(/function toggleHomeTheme\(/, "expected a landing-page theme toggle handler");
expect(/function syncHomeThemeUi\(/, "expected a home theme UI sync helper");
assert.doesNotMatch(html, /id="homeThemeToggleButton"/, "expected the landing-page dark mode toggle button to be hidden for now");
assert.doesNotMatch(html, /homeThemeToggleButton\?\.addEventListener\("click", toggleHomeTheme\)/, "expected the landing-page dark mode toggle click binding to be disabled for now");
expect(/transition:\s*max-height\s+0\.35s\s+ease/i, "expected smooth home explanation collapse transition");
expect(/id="queryPage"/, "expected a dedicated query page section");
expect(/id="csvPage"/, "expected a dedicated csv page section");
expect(/<option value="interviewprep">Interview Prep<\/option>/, "expected interview prep mode in the query mode dropdown");
expect(/id="interviewRoleGroup"/, "expected an interview role input group");
expect(/id="roleInput"/, "expected a dedicated role input for interview prep");
expect(/scripts\/csv-schema\.js/, "expected the page to load extracted csv schema helpers");
expect(/scripts\/csv-analytics\.js/, "expected the page to load extracted csv analytics helpers");
expect(/scripts\/csv-logging\.js/, "expected the page to load extracted csv logging helpers");
expect(/function getRouteFromLocation\(/, "expected a route parser");
expect(/function navigateTo\(/, "expected a navigation helper");
expect(/function applyRouteState\(/, "expected a route-driven visibility handler");
expect(/document\.body\.classList\.toggle\("home-dark-mode",\s*showHome\s*&&\s*state\.homeTheme\s*===\s*"dark"\)/, "expected home dark mode to apply only on the landing page");
expect(/function saveConnectionFromForm\(/, "expected a saveConnectionFromForm function");
expect(/function normalizeMetricValue\(/, "expected metric normalization helper for model-returned scores");
expect(/function renderMetricDirectionHint\(/, "expected metric direction hint renderer");
expect(/function renderIcon\(/, "expected shared inline SVG icon helper");
expect(/function runProviderRequest\(/, "expected a provider-agnostic request dispatcher");
expect(/function buildProviderRequest\(/, "expected provider request builders");
expect(/function parseProviderResponse\(/, "expected provider response parsers");
expect(/provider:\s*"openai"\s*\|\s*"anthropic"\s*\|\s*"gemini"\s*\|\s*"nvidia"/, "expected normalized provider shape documentation");
expect(/higher is better/i, "expected positive metric direction guidance in the UI");
expect(/lower is better/i, "expected negative metric direction guidance in the UI");
expect(/"\//, "expected root route handling in the UI");
expect(/["']\/query["']/, "expected query route handling in the UI");
expect(/["']\/csv["']/, "expected csv route handling in the UI");
expect(/["']\/api-key["']/, "expected api-key route handling in the UI");
expect(/\.agent-card\s*\{[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column/i, "expected agent cards to use consistent internal column layout");
expect(/\.mini-panel\s*\{[\s\S]*min-height:\s*\d+px/i, "expected mini panels to enforce consistent tile height");
expect(/\.section-intro\s*\{[\s\S]*display:\s*flex/i, "expected shared section intro alignment helper");
expect(/#queryPage \.utility-row\s*\{[\s\S]*flex-wrap:\s*nowrap/i, "expected query utility row to stay on one row at desktop widths");
expect(/#queryPage #statusMessage\s*\{[\s\S]*border-radius:\s*10px/i, "expected query status message to use a 10px border radius");
expect(/#queryPage #statusMessage\s*\{[\s\S]*margin-top:\s*26px/i, "expected query status message to align with the demo-topic chip row while staying in the same row");
expect(/\.aggregator-banner\s*\{[\s\S]*?border-radius:\s*10px/i, "expected the New Query aggregator banner to use a 10px border radius");
expect(/#csvPage\.query-panel\s*\{[\s\S]*border-radius:\s*10px/i, "expected CSV Analyst card to use a 10px border radius");
expect(/#csvResultSection\.brief-section\s*\{[\s\S]*border-radius:\s*10px/i, "expected generated CSV analysis card to use a 10px border radius");
expect(/#csvStatusMessage\s*\{[\s\S]*border-radius:\s*10px/i, "expected CSV status message to use a 10px border radius");
expect(/function renderCsvComparisonResult\(result, meta\) \{[\s\S]*brief-summary csv-summary-callout brief-card[\s\S]*Key Insight[\s\S]*file-overview-grid/, "expected compare-view Key Insight to use the single-file summary-callout style before file overview content");
expect(/\.quality-progress\s*\{[\s\S]*height:\s*4px[\s\S]*display:\s*flex/i, "expected normalized quality-progress sizing for equal bar heights");
expect(/\.quality-progress-fill\s*\{[\s\S]*height:\s*100%[\s\S]*display:\s*block/i, "expected quality-progress-fill to fully match the normalized track height");
expect(/\.quality-score-number\s*\{[\s\S]*dominant-baseline:\s*middle/i, "expected the CSV quality score text to be vertically centered");
expect(/class="quality-score-number" x="28" y="28"/, "expected the main CSV quality score number to sit in the middle of the ring");
expect(/<text x="20" y="20" style="font-size:10px;font-weight:500;fill:#1a1a2e;text-anchor:middle;dominant-baseline:middle;">\$\{escapeHtml\(quality\.overallScore\)\}<\/text>/, "expected compare-view mini quality ring text to be centered");
assert.doesNotMatch(html, /<h2 class="section-title" id="csvResultHeading" style="font-size:32px;">CSV Comparison Brief<\/h2>/, "expected the visible CSV Comparison Brief heading to be removed from compare view");
expect(/\.ui-icon\s*\{[\s\S]*display:\s*inline-block/i, "expected shared SVG icon styling");
expect(/\.tier-dot\s*\{[\s\S]*border-radius:\s*50%/i, "expected glossy tier dot styling for brief headings");
expect(/function renderTierDot\(kind\)/, "expected a dedicated tier dot helper for monitoring brief headings");
expect(/class="tier-title">\$\{renderTierDot\(kind\)\}<span>\$\{title\}<\/span>/, "expected monitoring brief headings to use tier dots instead of shared SVG icons");
expect(/id="brandMarkIcon"/, "expected the navbar brand mark to use an icon placeholder");
expect(/id="aggregatorBannerIcon"/, "expected the aggregator banner to use an icon placeholder");
expect(/class="button-icon"/, "expected the run button to use an icon wrapper");
expect(/function renderJobsMarkup\(/, "expected jobs card renderer");
expect(/Career Links/i, "expected jobs card to support careers and posting links");
expect(/<strong>Score<\/strong>[\s\S]*<strong>Velocity<\/strong>/, "expected Job Signal Tracker tiles to render Score before Velocity");
expect(/<strong>ESG<\/strong>[\s\S]*<strong>Risk<\/strong>/, "expected Regulatory & ESG Scanner tiles to render ESG before Risk");
expect(/\.agent-card-icon\s*\{[\s\S]*width:\s*44px[\s\S]*height:\s*44px[\s\S]*border-radius:\s*16px/i, "expected a shared dashboard agent icon container style");
expect(/class="brand-mark agent-card-icon"/, "expected agent dashboard cards to use the shared icon container class");
expect(/function normalizeJobLink\(/, "expected jobs link normalizer");
expect(/function resolveNewsSignalStrength\(/, "expected news signal-strength fallback helper");
expect(/function extractRelayErrorInfo\(/, "expected normalized relay error reader in the dashboard");
expect(/function buildFriendlyRelayErrorMessage\(/, "expected concise monitoring error messaging in the UI");
expect(/function setAgentCardVisibility\(/, "expected agent-card visibility helper for empty results");
expect(/function renderOptionalInfoNote\(/, "expected optional monitoring note renderer");
expect(/function renderOptionalTagRow\(/, "expected optional tag-row renderer");
expect(/function joinMarkupSections\(/, "expected monitoring card section join helper");
assert.doesNotMatch(html, /label:\s*"Sikich"/, "expected Sikich to be removed from New Query demo topics");
assert.doesNotMatch(html, /label:\s*"pharma industry"/i, "expected pharma industry to be removed from New Query demo topics");
assert.doesNotMatch(html, /No hot roles returned|No hiring signal returned|No opportunity signal returned|No recent headlines returned|No candidate themes surfaced|No peer interview patterns returned/, "expected monitoring cards to hide empty content instead of showing filler placeholders");
expect(/function syncQueryModeUi\(/, "expected query mode UI sync helper");
expect(/function getActiveAgentConfigs\(/, "expected mode-aware agent card configuration");
expect(/setRunButtonIdleState\(/, "expected a reusable idle-state renderer for the run button");
expect(/setRunButtonLoadingState\(/, "expected a reusable loading-state renderer for the run button");
expect(/function renderInterviewPrepBrief\(/, "expected a dedicated interview prep brief renderer");
expect(/function renderInterviewPrepNewsMarkup\(/, "expected interview prep agent card renderers");
expect(/Interview Prep Brief/i, "expected interview prep brief heading copy");
expect(/function renderInterviewPrepBrief\(result\) \{[\s\S]*brief-header[\s\S]*brief-header-side[\s\S]*Interview Prep Brief/i, "expected interview prep brief to use the shared brief header shell");
expect(/function renderInterviewPrepBrief\(result\) \{[\s\S]*csv-action-bar action-bar[\s\S]*Copy Summary[\s\S]*Download Brief/i, "expected interview prep brief to use the bottom action bar pattern");
assert.doesNotMatch(html, /function renderInterviewPrepBrief\(result\) \{[\s\S]*<div class="brief-actions"><button class="secondary-button" type="button" id="copyBriefButton">Copy to Clipboard<\/button><button class="secondary-button" type="button" id="downloadBriefButton">Download Brief<\/button>/, "expected interview prep brief to remove the old top-right brief-actions button row");
expect(/icon:\s*"news"|icon:\s*"jobs"|icon:\s*"sentiment"|icon:\s*"regulatory"|icon:\s*"competitor"/, "expected agent configs to use semantic icon names");
assert.doesNotMatch(html, /â—Œ|ðŸ|âš¡/, "expected broken mojibake icon glyphs to be removed from the monitoring UI");

console.log("PulseBoard structure assertions passed.");
