const fs = require("fs");
const assert = require("assert");

const page = fs.readFileSync("C:/Users/kim16/Videos/Pulseboard/index.html", "utf8");
const clientModulePaths = [
  "C:/Users/kim16/Videos/Pulseboard/scripts/csv-schema.js",
  "C:/Users/kim16/Videos/Pulseboard/scripts/csv-ingestion.js",
  "C:/Users/kim16/Videos/Pulseboard/scripts/csv-cleaning.js",
  "C:/Users/kim16/Videos/Pulseboard/scripts/csv-quality.js",
  "C:/Users/kim16/Videos/Pulseboard/scripts/csv-analytics.js",
  "C:/Users/kim16/Videos/Pulseboard/scripts/csv-logging.js"
];
const clientModules = clientModulePaths.map((filePath) => fs.readFileSync(filePath, "utf8")).join("\n");
const html = `${page}\n${clientModules}`;
const server = fs.existsSync("C:/Users/kim16/Videos/Pulseboard/server.js")
  ? fs.readFileSync("C:/Users/kim16/Videos/Pulseboard/server.js", "utf8")
  : "";

function expectIn(text, pattern, description) {
  assert.match(text, pattern, description);
}

function expectNotIn(text, pattern, description) {
  assert.doesNotMatch(text, pattern, description);
}

expectIn(html, /Analyze CSV/, "expected CSV Analyst entry action in the frontend");
expectIn(page, /scripts\/csv-schema\.js/, "expected external csv schema script loader");
expectIn(page, /scripts\/csv-ingestion\.js/, "expected external csv ingestion script loader");
expectIn(page, /scripts\/csv-cleaning\.js/, "expected external csv cleaning script loader");
expectIn(page, /scripts\/csv-quality\.js/, "expected external csv quality script loader");
expectIn(page, /scripts\/csv-analytics\.js/, "expected external csv analytics script loader");
expectIn(page, /scripts\/csv-logging\.js/, "expected external csv logging script loader");
expectIn(clientModules, /PulseBoardCsv/, "expected CSV helpers to be attached to a shared browser namespace");
expectIn(clientModules, /createCsvPipelineLogger/, "expected CSV pipeline logger helper");
expectIn(html, /id="csvPage"/, "expected dedicated CSV analysis page");
expectIn(html, /id="csvForm"/, "expected CSV upload form");
expectIn(html, /type="file"[^>]*accept="\.csv"/, "expected CSV file input");
expectIn(html, /id="clearCsvFileButton"/, "expected single-file CSV clear button");
expectIn(html, /id="clearCompareFileAButton"/, "expected compare File A clear button");
expectIn(html, /id="clearCompareFileBButton"/, "expected compare File B clear button");
expectIn(html, /Single File Analysis/i, "expected single-file CSV mode toggle");
expectIn(html, /Compare Two Files/i, "expected compare-two-files CSV mode toggle");
expectIn(html, /id="csvModeSingle"/, "expected single-file mode control");
expectIn(html, /id="csvModeCompare"/, "expected compare mode control");
expectIn(html, /id="compareFileAInput"/, "expected File A upload input");
expectIn(html, /id="compareFileBInput"/, "expected File B upload input");
expectIn(html, /id="compareLabelAInput"/, "expected File A label input");
expectIn(html, /id="compareLabelBInput"/, "expected File B label input");
expectIn(html, /function runCsvComparisonViaRelay\(/, "expected frontend CSV comparison relay helper");
expectIn(html, /function renderCsvComparisonResult\(/, "expected comparison result renderer");
expectIn(html, /Cross-Reference with Live Intelligence/i, "expected CSV cross-reference section heading");
expectIn(html, /function inferTopicFromCSV\(/, "expected CSV topic inference helper");
expectIn(html, /function buildCSVContext\(/, "expected CSV context builder for cross-reference");
expectIn(html, /function runCrossReference\(/, "expected cross-reference runner");
expectIn(html, /function runCrossReferenceViaRelay\(/, "expected cross-reference relay helper");
expectIn(html, /cross-ref-topic-input/, "expected editable cross-reference topic input");
expectIn(html, /Run Cross-Reference/i, "expected cross-reference launch action");
expectIn(html, /Re-run Cross-Reference/i, "expected cross-reference rerun action");
expectIn(html, /Internal × External Connections/i, "expected cross-reference connections section");
expectIn(html, /Gathering external intelligence/i, "expected cross-reference monitoring progress state");
expectIn(html, /Intelligence Synthesis/i, "expected synthesized cross-reference brief card");
expectIn(html, /function renderCrossReferenceSection\(/, "expected cross-reference section renderer");
expectIn(html, /function renderCrossRefBrief\(/, "expected cross-reference brief renderer");
expectIn(html, /chart\.umd\.min\.js/i, "expected Chart.js CDN loader");
expectIn(html, /Auto-Generated Charts/i, "expected auto-generated charts section");
expectIn(html, /function renderCharts\(/, "expected chart rendering engine");
expectIn(html, /function renderSingleChartFilterControls\(/, "expected single-file chart filter controls");
expectIn(html, /function buildSingleChartFilterOptions\(/, "expected single-file chart filter option builder");
expectIn(html, /function applySingleChartFilters\(/, "expected single-file chart filter application helper");
expectIn(html, /data-chart-filter="categoryColumn"|data-chart-filter="dateColumn"/, "expected chart filter controls in single-file view");
expectIn(html, /Reset filters/i, "expected chart filter reset action");
expectIn(html, /No rows match the current filters/i, "expected empty chart state for filtered-out data");
expectIn(html, /chart-meta-row|chart-meta-pill|chart-note-list|chart-note/i, "expected richer chart metadata and notes UI");
expectIn(html, /Distribution is highly skewed/i, "expected skew-aware histogram note");
expectIn(html, /function formatAxisValue\(/, "expected chart axis value formatter");
expectIn(html, /chartInstances/, "expected chart instance tracking for rerenders");
expectIn(html, /function renderChartSkeletons\(/, "expected chart skeleton renderer");
expectIn(html, /grouped_bar|line_comparison|side_by_side_bar/i, "expected comparison chart support");
expectIn(html, /downloadCsvPdfButton/, "expected CSV PDF download action");
expectIn(html, /downloadCsvComparisonPdfButton/, "expected comparison PDF download action");
expectIn(html, /function downloadCsvResultPdf\(/, "expected CSV PDF download handler");
expectIn(html, /function downloadBrief\(/, "expected shared CSV brief print helper");
expectIn(html, /function exportJSON\(/, "expected CSV JSON export helper");
expectIn(html, /function copyCsvSummaryToClipboard\(/, "expected CSV summary clipboard helper");
expectIn(html, /csv-action-bar/, "expected CSV action bar styling");
expectIn(html, /csvExportJsonButton/, "expected CSV JSON export button");
expectIn(html, /copyCsvSummaryButton/, "expected CSV copy summary button");
expectIn(html, /print-header/, "expected print-only CSV header");
expectIn(html, /document\.body\.classList\.add\(\"print-mode\"\)/, "expected print-mode body toggle before printing");
expectIn(html, /navigator\.clipboard\.writeText/, "expected clipboard copy support for CSV summary");
expectIn(html, /application\/json/, "expected JSON blob export for CSV analysis");
expectIn(html, /id="useSampleCsvButton"/, "expected sample CSV demo action");
expectIn(html, /SAMPLE_CSV_TEXT/, "expected built-in sample CSV data for demo use");
expectIn(html, /csv-metric-grid/, "expected executive CSV metric grid styling");
expectIn(html, /csv-insight-grid/, "expected structured CSV findings layout");
expectIn(html, /function runCsvAnalysisViaRelay\(/, "expected frontend CSV relay execution helper");
expectIn(html, /function applySampleCsv\(/, "expected sample CSV loader helper");
expectIn(html, /function clearSingleCsvSelection\(/, "expected single-file CSV clear helper");
expectIn(html, /function clearComparisonFileSelection\(/, "expected compare CSV clear helper");
expectIn(html, /function syncCsvFileClearButtons\(/, "expected CSV clear button visibility helper");
expectIn(html, /MAX_CSV_UPLOAD_BYTES/, "expected a hard single-file CSV size limit");
expectIn(html, /function validateAndReadCsvFile\(/, "expected CSV ingestion preflight helper");
expectIn(html, /UTF-8 BOM|UTF-16 LE|UTF-16 BE/i, "expected CSV encoding detection support");
expectIn(html, /unsupported file type|10 MB|file too large|encoding/i, "expected ingestion-specific CSV error messaging");
expectIn(html, /malformedRowCount|skippedRowNumbers|recoveredRowNumbers|warnings/, "expected structured CSV parse metadata");
expectIn(html, /malformed rows were skipped during upload/i, "expected malformed-row warning messaging");
expectIn(html, /function renderCsvInsightList\(/, "expected reusable CSV insight renderer");
expectIn(html, /function enrichAnomalyWithRow\(/, "expected anomaly row enrichment helper");
expectIn(html, /const idx = anomaly\.rowIndex/, "expected anomaly enrichment to use direct rowIndex");
expectIn(html, /matchedRow: sourceRows\[idx\]/, "expected direct anomaly row lookup from rowIndex");
expectIn(html, /anomalyExpandedState/, "expected per-card anomaly expansion state");
expectIn(html, /anomalyFilterState/, "expected anomaly filter state");
expectIn(html, /Anomalies Detected/i, "expected upgraded anomaly section heading");
expectIn(html, /View anomalous row/i, "expected anomaly row viewer trigger");
expectIn(html, /No matching row found/i, "expected unmatched anomaly fallback");
expectIn(html, /No anomalies detected/i, "expected anomaly empty state");
expectIn(html, /Critical only/i, "expected comparison anomaly filter tabs");
expectIn(html, /function renderAnomalySection\(/, "expected shared anomaly section renderer");
expectIn(html, /function renderAnomalyCard\(/, "expected anomaly card renderer");
expectIn(html, /function filterAnomalies\(/, "expected anomaly filter helper");
expectIn(html, /function severitySortRank\(/, "expected anomaly severity sorting helper");
expectIn(html, /function renderPlainComparisonAnomalySection\(/, "expected compare-mode plain anomaly renderer");
expectIn(html, /quality-preview-container|quality-inline-panel|quality-mini/i, "expected data quality UI");
expectIn(html, /Dataset Schema/i, "expected dataset schema section heading for single-file analysis");
expectIn(html, /function inferColumnSchema\(/, "expected schema inference helper");
expectIn(html, /function inferFullSchema\(/, "expected full schema inference helper");
expectIn(html, /function buildSchemaSummary\(/, "expected schema summary builder");
expectIn(html, /function computeCorrelations\(/, "expected single-file correlation helper");
expectIn(html, /function computeSegmentSummaries\(/, "expected single-file segmentation helper");
expectIn(html, /function buildCorrelationSummary\(/, "expected correlation summary builder");
expectIn(html, /function buildSegmentSummaryText\(/, "expected segment summary builder");
expectIn(html, /schemaExpanded/, "expected schema collapse state");
expectIn(html, /data-schema-toggle/, "expected schema collapse toggle");
expectIn(html, /Data Cleaning/i, "expected single-file data cleaning section");
expectIn(html, /function applyDataCleaningPipeline\(/, "expected reusable data cleaning pipeline entrypoint");
expectIn(html, /function applyNumericStandardization\(/, "expected numeric standardization step");
expectIn(html, /function applyCategoricalNormalization\(/, "expected categorical normalization step");
expectIn(html, /function applyMissingValueStrategies\(/, "expected missing value strategy application helper");
expectIn(html, /function dropRowsWithMissingValues\(/, "expected row-drop helper for missing values");
expectIn(html, /function buildCleaningDiffRows\(/, "expected cleaning diff preview row builder");
expectIn(html, /function renderCleaningDiffPreview\(/, "expected cleaning diff preview renderer");
expectIn(html, /mode:\s*"clean"/, "expected cleaning config to default to clean mode");
expectIn(html, /config\?\.mode === "raw"|normalizedConfig\.mode === "raw"/, "expected true raw mode branch in cleaning pipeline");
expectIn(html, /Cleaning Mode:/i, "expected cleaning mode control");
expectIn(html, /Numeric missing values:/i, "expected numeric missing strategy control");
expectIn(html, /Categorical missing values:/i, "expected categorical missing strategy control");
expectIn(html, /Drop rows with missing values/i, "expected row-drop control");
expectIn(html, /const dropRowsActive = Boolean\(config\.dropRowsWithMissing\)/, "expected row-drop override flag in cleaning UI");
expectIn(html, /data-numeric-missing-strategy \$\{rawMode \|\| dropRowsActive \? "disabled" : ""\}/, "expected numeric missing dropdown to disable when row dropping is active");
expectIn(html, /data-categorical-missing-strategy \$\{rawMode \|\| dropRowsActive \? "disabled" : ""\}/, "expected categorical missing dropdown to disable when row dropping is active");
expectIn(html, /Row dropping overrides fill strategies/i, "expected helper note when row dropping is enabled");
expectIn(html, /Fill with mean|Fill with median|Fill with zero|Fill with mode|Leave as-is/i, "expected missing-value strategy options");
expectIn(html, /numeric_standardization|categorical_normalization|missing_value_fill_mean|missing_value_fill_median|missing_value_fill_mode|missing_value_fill_zero|row_dropped_missing/i, "expected cleaning transformation types");
expectIn(html, /rawParsed|csvCleaningPreview|buildTransformationLogSummary/i, "expected single-file cleaning state and log summary support");
expectIn(html, /csvPipelineLogger|logCsvPipelineEvent|relay_request_started|brief_rendered/i, "expected structured CSV pipeline logging hooks");
expectIn(html, /Raw mode is active\. This file will be analyzed exactly as parsed/i, "expected raw-mode cleaning copy");
expectIn(html, /Raw parsed data will be analyzed unchanged/i, "expected raw-mode status message");
expectIn(html, /Changed Values Preview/i, "expected cleaning diff preview heading");
expectIn(html, /cleaning-diff-table/i, "expected diff preview UI");
expectNotIn(html, /function buildColumnCleaningSummaries\(/, "did not expect column-level cleaning summary builder");
expectNotIn(html, /function renderColumnCleaningSummary\(/, "did not expect column-level cleaning summary renderer");
expectNotIn(html, /cleaning-column-summary-grid|cleaning-column-card/i, "did not expect column summary UI classes");
expectIn(html, /Correlations/i, "expected correlations section in single-file brief");
expectIn(html, /Segment Breakdown/i, "expected segment breakdown section in single-file brief");
expectIn(html, /Strongest relationships|No strong numeric correlations/i, "expected correlation section copy");
expectIn(html, /No segmentation opportunities detected|top segments/i, "expected segmentation section copy");
expectIn(html, /function computeDataQualityReport\(/, "expected client-side data quality computation");
expectIn(html, /function computeCompleteness\(rows, headers\)/, "expected explicit completeness helper");
expectIn(html, /function isActuallyNumeric\(col, rows\)/, "expected numeric-column prefilter for validity scoring");
expectIn(html, /function isMissing\(value\)/, "expected shared missing-value helper for quality scoring");
expectIn(html, /trimmed === ''/, "expected empty strings to count as missing");
expectIn(html, /trimmed\.toLowerCase\(\) === 'n\/a'/, "expected n\/a missing detection");
expectIn(html, /trimmed === '#n\/a'/, "expected spreadsheet-style missing detection");
expectIn(html, /function computeCompleteness\(rows, headers\)/, "expected completeness helper implementation");
expectIn(html, /missingCount \+= 1/, "expected completeness to count missing cells");
expectIn(html, /affectedColumnCount: affectedColumns\.length/, "expected completeness to track affected columns");
expectIn(html, /if \(isMissing\(value\)\) continue/, "expected consistency\/validity checks to skip missing values");
expectIn(html, /const positiveOnlyCols = headers\.filter\(\(col\) => \{[\s\S]*\["price", "revenue", "amount", "cost", "total"\][\s\S]*isActuallyNumeric\(col, records\)/, "expected validity scoring to restrict positive-only columns to numeric revenue-style fields only");
expectIn(html, /function renderDataQualityCard\(/, "expected single-file quality card renderer");
expectIn(html, /function renderMiniQualitySummary\(/, "expected comparison quality summary renderer");
expectIn(html, /Completeness|Consistency|Uniqueness|Validity/, "expected quality score component labels");
expectIn(html, /Quality checked on 1,000 row sample/i, "expected sampled quality note for large files");
expectIn(html, /qualityPreviewContainer/, "expected quality preview container on CSV page");
expectIn(server, /Pre-computed data quality scores \(computed by JS, not estimated\):/i, "expected quality score context appended to CSV agent input");
expectIn(server, /Do not re-estimate quality scores/i, "expected server instructs model to use exact quality values");
expectIn(server, /Pre-computed column schema:/i, "expected schema summary context appended to CSV agent input");
expectIn(server, /Pre-computed correlations:/i, "expected correlation context appended to CSV agent input");
expectIn(server, /Pre-computed segment summaries:/i, "expected segment context appended to CSV agent input");
expectIn(server, /schemaSummary/, "expected single-file CSV relay to accept schema summary");
expectIn(server, /Client-side data cleaning summary:/i, "expected cleaning summary context appended to CSV agent input");
expectIn(server, /cleaningSummary|transformationLogSummary/, "expected single-file CSV relay to accept cleaning metadata");
expectIn(server, /Cleaning mode:/i, "expected relay cleaning context to include cleaning mode");
expectIn(server, /Missing values filled with mean|Missing values filled with median|Rows dropped due to missing values/i, "expected relay cleaning context to report missing-value handling");
expectIn(server, /The raw parsed dataset was analyzed unchanged\.|The cleaned dataset was analyzed using these exact transformations\./i, "expected mode-aware cleaning context wording");

expectIn(server, /\/api\/pulseboard\/analyze-csv/, "expected CSV relay endpoint");
expectIn(server, /\/api\/pulseboard\/compare-csv/, "expected CSV comparison relay endpoint");
expectIn(server, /\/api\/pulseboard\/cross-reference/, "expected cross-reference relay endpoint");
expectIn(server, /function analyzeCsvSession\(/, "expected CSV analysis relay function");
expectIn(server, /function compareCsvSession\(/, "expected CSV comparison relay function");
expectIn(server, /function crossReferenceSession\(/, "expected cross-reference relay function");
expectIn(server, /function parseCsvText\(/, "expected CSV parser");
expectIn(server, /function summarizeCsvData\(/, "expected CSV summarizer");
expectIn(server, /function runCsvAnalyst\(/, "expected CSV analyst model runner");
expectIn(server, /function runCsvComparisonAnalyst\(/, "expected CSV comparison agent runner");
expectIn(server, /chartRecommendations/i, "expected chart recommendation fields in CSV agent prompts");
expectIn(server, /grouped_bar|line_comparison|side_by_side_bar/i, "expected comparison chart recommendation prompt support");
expectIn(server, /declineColumns should include specific products or categories/i, "expected segment-level decline guidance in comparison prompt");
expectIn(server, /\$4\.50 net_revenue anomaly.*critical data quality issue/i, "expected explicit laptop anomaly instruction in comparison prompt");
expectIn(server, /function findAnomalyCandidates\(/, "expected JS anomaly candidate precomputation");
expectIn(server, /function isTransactionalDataset\(/, "expected transactional dataset guard for revenue-per-unit anomalies");
expectIn(server, /function deduplicateCandidatesByRow\(/, "expected row-level anomaly deduplication helper");
expectIn(server, /Each rowIndex should appear in your response at most ONCE/i, "expected prompt to limit anomalies to one per row");
expectIn(server, /Revenue per unit.*less than 1% of average/i, "expected revenue-to-units anomaly reason logic");
expectIn(server, /if \(zScore > 4\)/, "expected stricter anomaly z-score threshold");
expectIn(server, /const skipColumns = headers\.filter/, "expected business-variation skip columns for anomaly detection");
expectIn(server, /unit_price|discount_pct|satisfaction/i, "expected skip-column keywords in anomaly detection");
expectIn(server, /Focus on data QUALITY issues not business outliers/i, "expected prompt to focus on data quality anomalies");
expectIn(server, /Maximum 3 anomalies returned\./i, "expected tighter anomaly cap guidance");
expectIn(server, /rowIndex,\s*\/\/ exact index into rows array|rowIndex:/, "expected anomaly candidates to carry row indices");
expectIn(server, /function formatCandidatesForAgent\(/, "expected anomaly candidate formatter for agent input");
expectIn(server, /Pre-computed anomaly candidates:/i, "expected anomaly candidate context in agent input");
expectIn(server, /rowIndex: number[^]*copy EXACTLY from the candidate/i, "expected single-file prompt to require rowIndex echoing");
expectIn(server, /anomalousColumn: string[^]*copy the column name exactly from the candidate/i, "expected prompt to require anomalousColumn echoing");
expectIn(server, /Maximum 3 anomalies returned\./i, "expected capped anomaly count guidance");
expectIn(server, /anomalies: array of up to 3 objects \{ description: string, file: string, severity: string \}/i, "expected lighter compare anomaly contract");
expectIn(server, /function runCrossReferenceSynthesis\(/, "expected cross-reference synthesis runner");
expectIn(server, /connecting internal business data to external market intelligence/i, "expected cross-reference synthesis prompt");

console.log("PulseBoard CSV assertions passed.");
